#!/usr/bin/env python3
"""Write the `us-areas` pack: the `us` pack with one lineage region per
residence area (B at area level, spec 2026-10-01-ledger-areas.md).

Reads `worlds/us/data/places.bin` (format in distill_places.py) and writes
`worlds/us-areas/world.ron`, `places.ron` and `unions.ron` (markets by area,
a small national share):
- one region per area, named after it ("CA 2");
- founder_weight: the area's share of the 1840 population (Forstall county
  censuses, as distilled);
- immigrant_weight: a provisional proxy, the mean of the area's population
  shares in 1900 and 2020 (immigrants' destinations by era are debt);
- the parent pack's two regions, emptied (lists of records merge by id).

Run from the repository root:
    python3 internot_society/data/make_area_regions.py
"""

import os
import struct

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
PLACES = os.path.join(ROOT, "worlds", "us", "data", "places.bin")
OUT = os.path.join(ROOT, "worlds", "us-areas")


def main():
    b = open(PLACES, "rb").read()
    assert b[:8] == b"INTPLACE" and b[8] == 2, "needs places.bin version 2"
    pos = [9]

    def leb():
        n, shift = 0, 0
        while True:
            x = b[pos[0]]
            pos[0] += 1
            n |= (x & 0x7F) << shift
            shift += 7
            if x < 0x80:
                return n

    def text():
        n = b[pos[0]]
        s = b[pos[0] + 1 : pos[0] + 1 + n].decode("utf-8")
        pos[0] += 1 + n
        return s

    first, decades = struct.unpack_from("<HB", b, pos[0])
    pos[0] += 3
    areas = [text() for _ in range(leb())]
    zone_area = []
    for _ in range(leb()):
        leb()
        zone_area.append(leb())
        text()
    county_zone = []
    for _ in range(leb()):
        leb()
        county_zone.append(leb())
        text()
    cluster_county = [leb() for _ in range(leb())]
    weight = [[0] * decades for _ in areas]
    for _ in range(leb()):
        leb()
        pos[0] += 8
        area = zone_area[county_zone[cluster_county[leb()]]]
        for d in range(decades):
            weight[area][d] += leb()
    total = [sum(w[d] for w in weight) for d in range(decades)]
    d1840, d1900, d2020 = (1840 - first) // 10, (1900 - first) // 10, (2020 - first) // 10

    os.makedirs(OUT, exist_ok=True)
    lines = [
        "// The us pack with one lineage region per residence area (B at area",
        "// level, spec 2026-10-01-ledger-areas.md). Generated by",
        "// internot_society/data/make_area_regions.py from worlds/us/data/places.bin:",
        "// founder_weight is the area's share of the 1840 population; immigrant_weight",
        "// a provisional proxy, the mean of its shares in 1900 and 2020.",
        "(",
        '    name: "United States, area lineages",',
        '    description: "The us pack with one lineage region per residence area.",',
        '    extends: Some("us"),',
        "    regions: [",
        "        // The parent pack's two regions, emptied (lists merge by id).",
        '        (id: "east", founder_weight: 0.0, immigrant_weight: 0.0),',
        '        (id: "west", founder_weight: 0.0, immigrant_weight: 0.0),',
    ]
    for a, name in enumerate(areas):
        f = weight[a][d1840] / total[d1840]
        im = 0.5 * (weight[a][d1900] / total[d1900] + weight[a][d2020] / total[d2020])
        lines.append(f'        (id: "{name}", name: "{name}", founder_weight: {f:.6f}, immigrant_weight: {im:.6f}),')
    lines += ["    ],", ")", ""]
    with open(os.path.join(OUT, "world.ron"), "w") as f:
        f.write("\n".join(lines))
    with open(os.path.join(OUT, "unions.ron"), "w") as f:
        f.write(
            "// Markets by area: partners meet where they live. A small national\n"
            "// share pairs across areas (couples who met far apart); provisional,\n"
            "// calibrated on the share of natives living outside their birth state\n"
            "// (residence_realism) and on the about 25% of couples who lived more than\n"
            "// 50 km apart before moving in together (research note §5d).\n"
            "(\n"
            "    national_market_share: [(1840, 0.06), (1950, 0.08), (2020, 0.10)],\n"
            "    local_open_markets: true,\n"
            ")\n"
        )
    with open(os.path.join(OUT, "places.ron"), "w") as f:
        f.write(
            "// Each area is its own lineage region (the world region named after it).\n"
            "(\n    by_area: true,\n)\n"
        )
    print(f"{len(areas)} area regions written to {OUT}")


if __name__ == "__main__":
    main()
