[package]
name = "internot"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
procedural_core = { path = "../procedural_core" }
internot_society = { path = "../internot_society" }
chrono = { workspace = true }
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = { version = "1", features = ["chrono04"] }
thiserror = "1"

[dev-dependencies]
